trigger:
- main

stages:
- stage: BUILD
  jobs:
  - job: BasicReadiness
    pool:
      default
    steps:
    - task: PowerShell@2
      displayName: 'Verify changes on DEV env'
      inputs:
        targetType: 'inline'
        script: >
          liquibase --defaults-file=dev.properties validate

          liquibase --defaults-file=dev.properties status

          liquibase --defaults-file=dev.properties tag JOBID_$(Build.BuildId)
    - task: PowerShell@2
      displayName: 'Verify changes on PROD env'
      inputs:
        targetType: 'inline'
        script: >
          liquibase --defaults-file=prod.properties validate

          liquibase --defaults-file=prod.properties status

          liquibase --defaults-file=prod.properties tag JOBID_$(Build.BuildId)
- stage: DEV
  jobs:
  - job: DevDeployment
    pool:
      default
    steps:
    - task: PowerShell@2
      displayName: 'Test deploy on DEV'
      inputs:
        targetType: 'inline'
        script: >
          liquibase --defaults-file=dev.properties updateSQL 

          liquibase --defaults-file=dev.properties update
    - task: PowerShell@2
      displayName: 'Test rollback on DEV '
      inputs:
        targetType: 'inline'
        script: >
          liquibase --defaults-file=dev.properties rollbackSQL JOBID_$(Build.BuildId)
          
          liquibase --defaults-file=dev.properties rollback JOBID_$(Build.BuildId)
    - task: PowerShell@2
      displayName: 'Finalize deployment'
      inputs:
        targetType: 'inline'
        script: >
          liquibase --defaults-file=dev.properties update
- stage: CHECK
  jobs:
  - job: CompareEnv
    pool:
      default
    steps:
    - task: PowerShell@2
      displayName: 'Compare the environnements'
      inputs:
        targetType: 'inline'
        script: >
          liquibase --defaults-file=prod.properties diff
- stage: PROD
  jobs:
  - deployment: deployProd
    environment: PROD  
  - job: Testing
    pool:
      default
    steps:
    - task: PowerShell@2
      displayName: 'Test deploy on PROD'
      inputs:
        targetType: 'inline'
        script: >
          liquibase --defaults-file=prod.properties updateSQL 

          liquibase --defaults-file=prod.properties update
    - task: PowerShell@2
      displayName: 'Test rollback on PROD'
      inputs:
        targetType: 'inline'
        script: >
          liquibase --defaults-file=prod.properties rollbackSQL JOBID_$(Build.BuildId)
          
          liquibase --defaults-file=prod.properties rollback JOBID_$(Build.BuildId)
    - task: PowerShell@2
      displayName: 'Finalize deployment'
      inputs:
        targetType: 'inline'
        script: >
          liquibase --defaults-file=prod.properties update
