-- This files contains all the SQL that should be executed with SYSDBA to create 
-- a user called LB00 that will be used to store the liquibase objects
-- (DATABASECHANGELOG & DATABASECHANGELOGLOCK table)
-- using the liquibase.liquibaseSchemaName=LB00 line in the properties file

-- USER SQL
CREATE USER "LB00" IDENTIFIED BY "dev"  
DEFAULT TABLESPACE "SYSAUX"
TEMPORARY TABLESPACE "TEMP";

ALTER USER "LB00"
DEFAULT TABLESPACE "SYSAUX"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS

-- ROLES
GRANT "CONNECT" TO "LB00" ;
GRANT "RESOURCE" TO "LB00" ;
ALTER USER "LB00" DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES
GRANT CREATE SESSION TO "LB00" WITH ADMIN OPTION;
GRANT CREATE ANY INDEX TO "LB00" ;
GRANT CREATE VIEW TO "LB00" ;
GRANT CREATE SESSION TO "LB00" ;
GRANT SELECT ANY TABLE TO "LB00" ;
GRANT CREATE TABLE TO "LB00" ;
GRANT DROP ANY TABLE TO "LB00" ;
GRANT DROP ANY INDEX TO "LB00" ;
GRANT UPDATE ANY TABLE TO "LB00" ;
GRANT CREATE ANY VIEW TO "LB00" ;
GRANT INSERT ANY TABLE TO "LB00" ;
GRANT CREATE ANY TABLE TO "LB00" ;
GRANT DELETE ANY TABLE TO "LB00";
GRANT UNLIMITED TABLESPACE TO "LB00";

